### ISSUE TITLE
Commenting 404

### ISSUE THREAD

**Issue by lorensr** [OneGraph/onegraph-changelog#79]
Clicking the comment icon here:

![image](https://user-images.githubusercontent.com/251288/107088983-de44b980-67cb-11eb-9fdf-2ccc27f9f334.png)
https://www.onegraph.com/changelog

takes me to this page:

https://www.onegraph.com/changelog/post/72/support-for-githubs-expiring-tokens#comments

![image](https://user-images.githubusercontent.com/251288/107088969-d553e800-67cb-11eb-8ab6-4fbbf4975acd.png)

**Comment by dwwoelfel** [comment]
How weird! There must be some bug in the client-side routing b/c going to that url directly works. 

I'll take a closer look later tonight. Thanks for the report!

**Comment by lorensr** [comment]
Ha, so it does ☺️

**Comment by dwwoelfel** [comment]
Fixed now! Thanks again for reporting.

I had a heck of a time debugging, because it only happens if you set a `basePath` in the `.next.config.js` (in our case the basePath is `/changelog`, but I don't usually set it when developing locally). 

I updated to next.js 10.0.6 with this fix https://github.com/vercel/next.js/commit/97e9d54f2edb4435ef9b803898d69b97817306fa and now all is well.
